### ISSUE TITLE
Error in correlation between taxa abundance and environmental variables in microbiomeseq

### ISSUE THREAD

**Issue by smmontanos** [umerijaz/microbiomeSeq#27]
The package Microbiomeseq in R helps me a lot, however, I have an issue when I tried to run taxa.env.correlation, with this code in R:

`phyfa <- taxa_level(physeq, "Family")
env.taxa.cor <- taxa.env.correlation(phyfa, grouping_column = "Specie", method = "pearson", pvalue.threshold = 0.05, padjust.method = "BH", adjustment = 5, num.taxa = 10, select.variables = NULL)`

Error in cor.test.default(a[complete.cases(b), ], b[complete.cases(b),  : 
  not enough finite observations

I don´t know what is the problem, because I update all necessary packages for microbiomeseq, and I have phyloseq object correctly. Any suggestions and help to do this analysis plotting the results???

**Comment by AlfredUg** [comment]
Hey @smmontanos, 
The issue has been fixed, re-install microbiomeSeq and re-run your analysis. It should work fine, let us know if it doesn't.

**Comment by smmontanos** [comment]
Hello @AlfredUg  ,

I don´t know what happend, but the error still in my code !!!

**Comment by aimeelmassey** [comment]
I am having this same issue - my phyloseq object works with other functions but not taxa.env.correlation. My OTU abundance matrix has some NA's but I have tried including samples and OTU's with the least amount of NA's and I still receive this error.

**Comment by carloshenriquezc** [comment]
Hello,

Thanks for sharing your routine, 

I still having the same issue: 

Error in cor.test.default(a[complete.cases(b), ], b[complete.cases(b),  : 
  not enough finite observations

**Comment by Catastrofix** [comment]
I am having the same issue, is there a way to solve this problem?

**Comment by NataliHB** [comment]
I have the same issue, Does anyone now how to fix it?
