### ISSUE TITLE
taxa_level() - Error in as(x, "matrix")[i, j, drop = FALSE] : subscript out of bounds

### ISSUE THREAD

**Issue by GeoMicroSoares** [umerijaz/microbiomeSeq#3]
Hi there,

The package looks quite cool, looking forward for the stable version! Keep up the good work!

Here's the error I'm getting:
```
> data("GlobalPatterns")
> physeq <- taxa_level(GlobalPatterns, which_level = "Genus")
Error in as(x, "matrix")[i, j, drop = FALSE] : subscript out of bounds
```
Going a bit deeper into it, RStudio tells me the debug location is around these lines of code within taxa_level():
```
14    for (i in list) {
15      tmp <- data.frame(rowSums(OTU[, rownames(OTU_taxonomy)[OTU_taxonomy[, 
16        which_level] == i]]))
```
Tried to replicate it myself with GlobalPatterns and this seems to be the main issue:
```
> rowSums(OTU[, rownames(OTU_taxonomy)])
Error in as(x, "matrix")[i, j, drop = FALSE] : subscript out of bounds
```
I'm not sure what the aim of this part of the script is but the names do match:
```
> str(rowSums(OTU))
 Named num [1:19216] 259 8 1 51 3 4 11 1 352 8 ...
 - attr(*, "names")= chr [1:19216] "549322" "522457" "951" "244423" ...
> str(rownames(OTU_taxonomy))
 chr [1:19216] "549322" "522457" "951" "244423" "586076" "246140" "143239" "244960" "255340" "144887" "141782" ...
```
Hope this helps!

**Comment by AlfredUg** [comment]
@GeoMicroSoares , Thanks for this, let's look at this, I will notify you as soon as this is fixed.

**Comment by AlfredUg** [comment]
@GeoMicroSoares, this issue has been fixed, it should work well now. Thanks

**Comment by GeoMicroSoares** [comment]
Working now for me as well!

**Comment by Stabilo12** [comment]
Hi, 
I still have the same error.. 

> data("GlobalPatterns")
> physeq <- taxa_level(GlobalPatterns, which_level = "Genus")
Error in as(x, "matrix")[i, j, drop = FALSE] : subscript out of bounds
(I use version 0.1.)

Suggestions are welcome :)

**Comment by AlfredUg** [comment]
Hey @Stabilo12,

A quick work around would be to transpose the `phyloseq` object before hand, something like;
`physeq <- taxa_level(t(GlobalPatterns), which_level = "Genus")` .
I hope that helps.
